name: Merge to Develop and Release-Candidate

on:
  workflow_dispatch:

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure Git
        run: |
            git config --global user.email emuhnas1@hotmail.com
            git config --global user.name init-iator

      - name: Merge main to develop
        run: |
            git checkout develop
            git pull
            git merge main
            git push

      - name: Merge main to release-candidate
        run: |
          git checkout release-candidate
          git pull
          git merge main
          git push